### PR TITLE
Auto-build index with `pysam.FastaFile`

### PR DESCRIPTION
**Pull request by valentynbez**
- All functionality from `Biopython` can be replaced with `pysam`
- `pysam` automatically builds `.fai` index - less code
- `pysam` is 2x faster and scales better
- end codon from `Prodigal` is automatically handled during sequence loading
- tqdm progress bar is implemented 
---
### Found BUG: 
- during building `bagel.fa`
```
[W::fai_insert_index] Ignoring duplicate sequence "Plantazolicin" at byte offset 5186
[W::fai_insert_index] Ignoring duplicate sequence "Butyrivibriocin" at byte offset 13461
....
```
Identical headers were silently dropped in the previous code, and only the last seq was considered in the output. Now `pysam.FastaFile` throws a warning.

## TODO
- correct requirements in `DeepBLAST` repo 
- correct docs

### CODE REVIEW

**Comment by mortonjt** [comment]
Thanks for putting this together! I’ll need to pull down / test on my end next week, but from a first pass this looks promising.

**Comment by valentynbez** [comment]
No problem, there is still a thing I am currently working on that might improve the project from a purely engineering standpoint. 
Stay tuned :D

**Comment by mortonjt** [comment]
Hi @valentynbez thanks for the contribution.  Just to clarify, the fasta index is built on the fly in pysam, correct?
Is this PR ready for review / testing?

**Comment by valentynbez** [comment]
Hi! 
Yes. I added few additional features for convenience: 
- automatically handling stop codon for Prodigal input ("*") - otherwise protobuf errors - I think it will be a frequent use case
- tqdm progressbar for database build. 

PR is ready, I tested everything on my side.

**Comment by mortonjt** [comment]
Hi @valentynbez thanks for the contribution. Yes I have confirmed that this works -- we'll need the setup.py updated to include pysam.  But otherwise I think we can merge this in.

**Pull request merged**
